# Usar imagen oficial de Node.js
FROM node:20.8.0-slim

# Establecer el directorio de trabajo
# WORKDIR /usr/src/app

# Copiar package.json y package-lock.json
# COPY package*.json ./

# Instalar dependencias
# RUN npm install

# # Copiar el resto de los archivos del proyecto
# COPY . .

# # Exponer puerto 3000 (o el puerto que desees)
EXPOSE 3000

# # Comando por defecto para ejecutar la app
# CMD [ "node", "index.js" ]
